#!/bin/bash

# ARDEN Session Stop Hook
# Automatically executed when a Claude Code session ends
# Captures learnings, summarizes session, and archives outputs

ARDEN_HOME="$HOME/ARDEN"
SESSION_DATE=$(date +%Y-%m-%d)
SESSION_DIR="$ARDEN_HOME/history/sessions/$SESSION_DATE"

# Find the most recent session file
SESSION_FILE=$(find "$SESSION_DIR" -name "session_*.md" -type f 2>/dev/null | sort -r | head -n 1)

if [ -z "$SESSION_FILE" ]; then
  echo "⚠️  No active session found"
  exit 0
fi

# Append session end info
cat >> "$SESSION_FILE" << EOF

## Session End
- End Time: $(date +%H:%M:%S)
- Duration: [Auto-calculated]

## Summary
[Session summary will be generated by Claude Code]

## Next Steps
[Any pending tasks or follow-ups]

---
Session closed successfully.
EOF

echo "💾 Session saved: $SESSION_FILE"

# Prompt for learnings extraction (if in interactive session)
if [ -t 0 ]; then
  echo ""
  echo "📚 Would you like to extract learnings from this session?"
  echo "   (Learnings help ARDEN improve over time)"
fi

# Clean up temporary files
find "$ARDEN_HOME/voice/recordings" -name "*.ogg" -mtime +7 -delete 2>/dev/null
find "$ARDEN_HOME/voice/responses" -name "*.mp3" -mtime +7 -delete 2>/dev/null

echo "✅ Session closed. ARDEN standing by."
